preset: conventionalcommits
branches:
  - name: main
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: revert
          release: patch
        - type: perf
          release: patch
  # Block major version upgrades due to us not supporting them that well. This can
  # be disabled by setting releaseOptions.allowMajorVersions, but be warned this
  # is not well supported for services.
  - - "@semantic-release/exec"
    # We use generateNotesCmd instead of verifyConditionsCmd because it has access
    # to last/nextRelease due to when the step runs.
    - generateNotesCmd: |-
        ./scripts/shell-wrapper.sh major-release-checker.js ${lastRelease.version} ${nextRelease.version}

  # This creates fancy release notes in our Github release
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"

  ### Block(customReleasePlugins)
  # Build and push our docker images for actions
  - - "@semantic-release/exec"
    # Using generateNotesCmd just to get it to run on dryrun because `prepare` is skipped
    - generateNotesCmd: "APP_VERSION=development ./scripts/docker.sh"
  - - "@semantic-release/exec"
    - publishCmd: "APP_VERSION=${nextRelease.version} ./scripts/docker.sh"
  ### EndBlock(customReleasePlugins)
