# Docs: https://docs.cortex.io/docs/reference/basics/entities#service-entities

openapi: 3.0.0
info:
  title: actions
  description: >
    This is a collection of actions that are used by Outreach.
  x-cortex-type: service
  x-cortex-slack:
    channels:
      - name: dev-tooling-design
        notificationsEnabled: false
      - name: dev-tooling-support
        notificationsEnabled: false
      - name: dt-oncall
        notificationsEnabled: true
      - name: fnd-dt-alerts
        notificationsEnabled: true
  x-cortex-owners:
    - type: group
      name: fnd-dt
      provider: CORTEX
  x-cortex-tag: actions
  x-cortex-git:
    github:
      repository: getoutreach/actions
  x-cortex-oncall:
    pagerduty:
      id: P9HJAUT
      type: SERVICE
  x-cortex-link:
    ## These are useful documentation links for this service. Please fill in the customLinks block if you have additional documentation links.
    ## name: The name of the link
    ## type: Choose one type from (dashboard,documentation,healthcheck,logs,metrics,runbook)
    ## url: The link url
    ## description(optional): Description to this link
    - name: API Docs
      type: api_documentation
      url: https://engdocs.outreach.cloud/github.com/getoutreach/actions#section-readme
    ## <<Stencil::Block(customLinks)>>
    ## <</Stencil::Block>>
  x-cortex-custom-metadata:
    app: actions
    name: actions
    repo: https://github.com/getoutreach/actions
    framework: stencil
    language: Golang
    stencil_version: v1.43.0
    golang_version: 1.23.4
    cli: false
    service: false
    product: Outreach
    lifecycle: public_ga
    ## <<Stencil::Block(extraAliases)>>
    ## <</Stencil::Block>>
    reporting_team: fnd-dt
    lintroller: platinum
  x-cortex-groups:
    - lifecycle:public_ga
    - product:Outreach
    - language:Golang
    - framework:stencil
    - engOrg:fnd
