[tools]
act = "v0.2.26"

[tasks."test:actions"]
description = "Run tests on all actions"
depends = ["test:actions:*"]

[tasks."test:actions:brokenbranch"]
description = "Run tests on brokenbranch action"
run = "./scripts/test-action.sh brokenbranch"

[tasks."test:actions:commitguard"]
description = "Run tests on commitguard action"
run = "./scripts/test-action.sh commitguard"

[tasks."test:actions:conventional_commit"]
description = "Run tests on conventional_commit action"
run = "./scripts/test-action.sh conventional_commit"
