[task_config]
includes = [".bootstrap/.mise/tasks"]

## <<Stencil::Block(customMiseEnvironment)>>

## <</Stencil::Block>>

[tools]
"npm:prettier" = "2"

## <<Stencil::Block(customMiseTools)>>
act = "latest"
## <</Stencil::Block>>

## <<Stencil::Block(extraMise)>>

## <</Stencil::Block>>
