# Please re-run stencil after any changes to this file as invalid
# syntax, such as anchors, will be fixed automatically.
version: 2.1
orbs:
  shared: getoutreach/shared@2.5.0

# Extra contexts to expose to all jobs below
contexts: &contexts
  - aws-credentials
  - npm-credentials
  - prismacloud-credentials
  - opslevel-credentials
  - vault-dev
  - confluence
  ## <<Stencil::Block(extraContexts)>>
  - docker-registry
  - ghaccesstoken
  ## <</Stencil::Block>>

# Branches used for releasing code, pre-release or not
release_branches: &release_branches
  - "main"

jobs:
  {}
  ## <<Stencil::Block(circleJobs)>>

  ## <</Stencil::Block>>

  ### Start jobs inserted by other modules
  ### End jobs inserted by other modules

workflows:
  version: 2
  ## <<Stencil::Block(circleWorkflows)>>

  ## <</Stencil::Block>>

  ### Start workflows inserted by other modules
  ### End workflows inserted by other modules

  release:
    jobs:
      ## <<Stencil::Block(circleWorkflowJobs)>>

      ## <</Stencil::Block>>
      ### Start jobs inserted by other modules
      ### End jobs inserted by other modules
      - shared/release: &release
          dryrun: false
          context: *contexts
          ## <<Stencil::Block(circleReleaseExtra)>>
          machine: true
          executor:
            name: shared/testbed-machine
          resource_class: large
          ## <</Stencil::Block>>
          requires:
            ## <<Stencil::Block(circleReleaseRequires)>>

            ## <</Stencil::Block>>
            - shared/test
          filters:
            branches:
              only: *release_branches

      # Dryrun release for PRs.
      - shared/release:
          <<: *release
          dryrun: true
          filters:
            branches:
              ignore: *release_branches
      - shared/test:
          context: *contexts
          app_name: actions
          ### Start parameters inserted by other modules
          ### End parameters inserted by other modules
          ## <<Stencil::Block(circleTestExtra)>>

          ## <</Stencil::Block>>

      - shared/publish_docs:
          context: *contexts
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - shared/e2e:
          context: *contexts
          ## <<Stencil::Block(circleE2EExtra)>>

          ## <</Stencil::Block>>
      - shared/docker:
          context: *contexts
          filters:
            branches:
              ignore: *release_branches
            tags:
              only: /v\d+(\.\d+)*(-.*)*/
