#!/usr/bin/env bash
#
#MISE description="Syncs Go version with Stencil-unmanaged Dockerfile"

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ROOT_DIR="$DIR/../../../.."
DEVBASE_LIB_DIR="$ROOT_DIR/.bootstrap/shell/lib"

"$ROOT_DIR"/scripts/devbase.sh

# shellcheck source=../../../../.bootstrap/shell/lib/logging.sh
source "$DEVBASE_LIB_DIR"/logging.sh

# shellcheck source=../../../../.bootstrap/shell/lib/sed.sh
source "$DEVBASE_LIB_DIR"/sed.sh

goVersion="$(grep "^golang " "$ROOT_DIR"/.tool-versions | awk '{print $2}')"

info "Syncing Go version in Dockerfile"

sed_replace '\(FROM golang\):[.0-9]\+ \(AS builder\)' "\1:$goVersion \2" \
	"$ROOT_DIR"/Dockerfile
