# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: commitguard
on:
  workflow_call:
    secrets:
      OUTREACH_DOCKER_JSON:
        required: true
      PAT_OUTREACH_CI:
        required: false
    inputs:
      image_tag:
        type: string
        default: latest
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/outreach-docker/actions/commitguard:${{ inputs.image_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PAT_OUTREACH_CI: ${{ secrets.PAT_OUTREACH_CI }}
      credentials:
        username: _json_key
        password: ${{ secrets.OUTREACH_DOCKER_JSON }}
    steps:
      - run: /usr/local/bin/action
