# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: contentional_commit
on:
  workflow_call:
    secrets:
      PAT_OUTREACH_CI:
        required: false
    inputs:
      image_tag:
        type: string
        description: "Image to use for the action"
        default: latest
        required: false
      bypass_author_emails:
        type: string
        description: "Space separated list of emails to bypass the conventional commit check"
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/getoutreach/action-conventional_commit:${{ inputs.image_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PAT_OUTREACH_CI: ${{ secrets.PAT_OUTREACH_CI }}
        BYPASS_AUTHOR_EMAILS: ${{ inputs.bypass_author_emails }}
    steps:
      - run: /usr/local/bin/action
