# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: opslevel
on:
  workflow_call:
    secrets:
      OUTREACH_DOCKER_JSON:
        required: true
      SLACK_TOKEN:
        required: true
      OPSLEVEL_TOKEN:
        required: true

    inputs:
      image_tag:
        type: string
        default: latest
        required: false
      branch:
        type: string
        default: main
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/outreach-docker/actions/opslevel:${{ inputs.image_tag }}
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        OPSLEVEL_TOKEN: ${{ secrets.OPSLEVEL_TOKEN }}
      credentials:
        username: _json_key
        password: ${{ secrets.OUTREACH_DOCKER_JSON }}
    steps:
      - run: /usr/local/bin/action
